apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: multik8s-com-tls
spec:
  secretName: multik8s-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multik8s.com
  dnsNames:
    - multik8s.com
    - www.multik8s.com
