name: build_poc
on:
  push:
    branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - uses: azure/docker-login@v1
          with:
            login-server: devnextgen.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t devnextgen.azurecr.io/nodejssampleapp:${{ github.sha }}
            docker push devnextgen.azurecr.io/nodejssampleapp:${{ github.sha }}
