name: build_poi
on:
  push:
    paths:
      - "mrajan-rsi/multi-k8s/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Container Registry Build
        uses: ams0/acr-task-github-action@v2

        with:
          service_principal: ${{ secrets.REGISTRY_USERNAME }}
          service_principal_password: ${{ secrets.REGISTRY_PASSWORD }}
          tenant: ${{ secrets.TENANT }}
          registry: ${{ secrets.REGISTRY }}
          repository: ${{ secrets.REPOSITORY }}
          image: poi
          #git_access_token: ${{ secrets.git_access_token }}
          folder: mrajan-rsi/multi-k8s
          #dockerfile: ../../dockerfiles/Dockerfile_3
